# Default values for helm-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

fullnameOverride : ""
image:
  repository: ""
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

container:
  name: ""
  services: []

hasendpoint: true

service:
  type: LoadBalancer
  port: 80
  name: api
  annotations: "{\"ports\": {\"80\":\"my-backendconfig\"}}"
  targetport: 80
  namespace: default
  healthcheckpath: /.well-known/apollo/server-health

ingress:
  enabled: false
  ManagedCertificate: 
    name: &ManagedCertificate ""
  FrontendConfig:
    name: &FrontendConfig ""
  BackendConfig:
    name: my-backendconfig-graphql
  annotations: 
    kubernetes.io/ingress.global-static-ip-name: ""
    networking.gke.io/managed-certificates: *ManagedCertificate
    networking.gke.io/v1beta1.FrontendConfig: *FrontendConfig
  hosts:
    - host: ""
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: api
            port:
              number: 3000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

environment:
  env:
    PORT: 80
    NODE_ENV: development
    NAMESPACE: mp
    MC_TRANSPORTER_TYPE: "NATS"
    MC_TRANSPORTER: "{\"servers\":\"nats://nats.development.svc.cluster.local\"}"
    TRANSPORTER: redis://redis-master.test.svc.cluster.local
    REDIS_PORT: 6379
    APOLLO_SCHEMA_REPORTING: false
  secret:
    secret: ""