apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
     {{- include "helm-charts.labels" . | nindent 4 }}
    service: api
spec:
  selector:
    matchLabels:
      {{- include "helm-charts.selectorLabels" . | nindent 6 }}
      service: api
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "helm-charts.selectorLabels" . | nindent 8 }}
        service: api
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.repository }}:{{ $.Values.image.tag }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
            - secretRef:
                name: {{ .Release.Name }}-secret
          {{- if .Values.container.healthcheckenabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.service.targetport }}
              port: {{ .Values.container.healthcheckurl | quote }}
            initialDelaySeconds: 10
            periodSeconds: 5
          {{ end }}
---