{{- $fullName := .Values.service.name -}}
{{- $svcPort := .Values.service.port -}}
{{- if .Values.ingress.enabled -}}
#########################################################
# Managed Certificate
#########################################################
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: app-cert-managment
  labels:
    name: app-cert-managment
spec:
  domains:
    {{- range .Values.ingress.hosts }}
    - {{ .host | quote }}
    {{- end }}
---
#########################################################
# FrontendConfig
#########################################################
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: frontendconfig
  labels:
    name: frontendconfig
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
---
#########################################################
# BackendConfig
#########################################################
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-backendconfig-graphql
spec:
  healthCheck:
    checkIntervalSec: 15
    type: HTTP
    requestPath: {{ .Values.service.healthcheckpath }} 
---
#########################################################
# Ingress
#########################################################
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "helm-charts.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}