{{if .Values.hasendpoint }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | quote }}
  labels:
      {{- include "helm-charts.labels" . | nindent 4 }}
  {{- if .Values.ingress.enabled -}}
  annotations:
    cloud.google.com/backend-config: {{ .Values.service.annotations }}
  {{- end }}
spec:
  selector:
     {{- include "helm-charts.selectorLabels" . | nindent 4 }}
    service: api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
  type: {{ .Values.service.type }}
{{ end }}
---